
/*
How to create Put and Patch Request
-----------------------------------

In a playwright , creating PUT and PATCH request is very simmilar to creating a POST request.
The only difference is the HTTP method (request.put() or similar request.patch()).

PUT is generally used to replace  the entire resource.

PATCH is used to update only specific fields of an existing resource.

Eg. Update only th same name or price
we will crteate the put /patch request and then validation of response.
sample API server = https://restful-api.dev/
*/

import{test,expect} from '@playwright/test'


test('PatchDemo', async ({request})=>{

 const response = await request.patch('https://api.restful-api.dev/objects/ff8081819f7e10ae019f93c5171c1fc6', {
    headers:{
        'Content-Type': 'application/json'
    },

    data:{
      name: 'HP Microprocerssor Laptop Pro 21',
    }
 })
  const responsebody = await response.json();
  console.log(await responsebody);
  expect(responsebody.name).toBe('HP Microprocerssor Laptop Pro 21');
  // id is generated by the server; assert it exists and is a string
   
  });





