/*.
POst request (creation and validation)
---------------------------------------
PostRequest is used when we need to create a new record/dat on the server

when Post request is sent , request data also  need to be sent which is commonly in json.
Also, a header (content -type) needs to sent along with request.
content-Type header is explicit declaration of type of content being sent by client so server can process it accoordingly and there is not  confusion about it.
we will create the post request, response will be received and then validation of response.

simple AP[I Server = https://restful-api.dev/

*/

import {test,expect} from '@playwright/test'

test('PostDemo', async ({request})=>{

 const response = await request.post('https://api.restful-api.dev/objects', {
    headers:{
        'Content-Type': 'application/json'
    },

    data:{
      name: 'Apple Laptop Pro 19',
      data: {
        year: 2026,
        price: 1999.99,
        "CPU model": 'A10 Processor Core 10',
        "Hard disk size": '12 TB'
      }
    }
 })
  const responsebody = await response.json();
  console.log(responsebody);

  expect(responsebody.name).toBe('Apple Laptop Pro 19');
  // id is generated by the server; assert it exists and is a string
  expect(typeof responsebody.id).toBe('string');
  expect(responsebody.data).toEqual({
    year: 2026,
    price: 1999.99,
    "CPU model": 'A10 Processor Core 10',
    "Hard disk size": '12 TB'
  });






})