/*
How to create Put and Patch Request
-----------------------------------

In a playwright , creating PUT and PATCH request is very simmilar to creating a POST request.
The only difference is the HTTP method (request.put() or similar request.patch()).

PUT is generally used to replace  the entire resource.

PATCH is used to update only specific fields of an existing resource.

Eg. Update only th same name or price
we will crteate the put /patch request and then validation of response.
sample API server = https://restful-api.dev/
*/

import{test,expect} from '@playwright/test'


test('PutDemo', async ({request})=>{

 const response = await request.put('https://api.restful-api.dev/objects/ff8081819f7e10ae019f93c5171c1fc6', {
    headers:{
        'Content-Type': 'application/json'
    },

    data:{
      name: 'ASUS Laptop Pro 19',
      data: {
        year: 2026,
        price: 49999.99,
        "CPU model": 'I5 2nd generation Processor Core 10',
        "Hard disk size": '1 TB'
      }
    }
 })
  const responsebody = await response.json();
  console.log(responsebody);

  expect(responsebody.name).toBe('ASUS Laptop Pro 19');
  // id is generated by the server; assert it exists and is a string
  expect(typeof responsebody.id).toBe('string');
  expect(responsebody.data).toEqual({
    year: 2026,
        price: 49999.99,
    "CPU model": 'I5 2nd generation Processor Core 10',
        "Hard disk size": '1 TB'
  });






})